<?php
// status file -- auto generated by monitor.pl on 2009/03/01.22:02:21

$status['data_extractor'] = 'good';
$status['quick_look'] = 'good';
$status['contour'] = 'good';
$status['grid'] = 'good';
$status['o3_db'] = 'good';

?>
